export default {
  REGISTER: 'auth/REGISTER',
  REGISTER_SUCCESS: 'auth/REGISTER_SUCCESS',
  REGISTER_FAILED: 'auth/REGISTER_FAILED',
  LOGIN: 'auth/LOGIN',
  LOGIN_FAILED: 'auth/LOGIN_FAILURE',
  LOGIN_COMPLETED: 'auth/LOGIN_SUCCESS',
  LOGOUT: 'auth/LOGOUT',
  REFRESH_JWT: 'auth/REFRESH_JWT',
  REFRESH_JWT_FAILED: 'auth/REFRESH_JWT_FAILED',
  REFRESH_JWT_COMPLETED: 'auth/REFRESH_JWT_COMPLETED'
};
