const LOGIN = 'auth/LOGIN';
const LOGIN_FAILED = 'auth/LOGIN_FAILURE';
const LOGIN_COMPLETED = 'auth/LOGIN_SUCCESS';
const LOGOUT = 'auth/LOGOUT';
const REFRESH_JWT = 'auth/REFRESH_JWT';
const REFRESH_JWT_FAILED = 'auth/REFRESH_JWT_FAILED';
const REFRESH_JWT_COMPLETED = 'auth/REFRESH_JWT_COMPLETED';

export default {
  LOGIN,
  LOGIN_COMPLETED,
  LOGIN_FAILED,
  LOGOUT,
  REFRESH_JWT,
  REFRESH_JWT_COMPLETED,
  REFRESH_JWT_FAILED
};
