const POPULATE_BESTIARY = 'bestiary/POPULATE_BESTIARY';
const POPULATE_BESTIARY_COMPLETE = 'bestiary/POPULATE_BESTIARY_COMPLETE';
const POPULATE_BESTIARY_CANCELLED = 'bestiary/POPULATE_BESTIARY_CANCELLED';
const RECEIVE_BESTIARY_DATA = 'bestiary/RECEIVE_BESTIARY_DATA';
const CHANGE_PAGE = 'bestiary/CHANGE_PAGE';

export default {
  POPULATE_BESTIARY,
  POPULATE_BESTIARY_COMPLETE,
  POPULATE_BESTIARY_CANCELLED,
  RECEIVE_BESTIARY_DATA,
  CHANGE_PAGE
};
