export default {
  POPULATE_BESTIARY: 'bestiary/POPULATE_BESTIARY',
  POPULATE_BESTIARY_COMPLETE: 'bestiary/POPULATE_BESTIARY_COMPLETE',
  POPULATE_BESTIARY_CANCELLED: 'bestiary/POPULATE_BESTIARY_CANCELLED',
  GET_MONSTER: 'bestiary/GET_MONSTER',
  GET_MONSTER_COMPLETE: 'bestiary/GET_MONSTER_COMPLETE',
  GET_MONSTER_FAILED: 'bestiary/GET_MONSTER_FAILED',
  GET_SKILL: 'bestiary/GET_SKILL',
  GET_SKILL_COMPLETE: 'bestiary/GET_SKILL_COMPLETE',
  GET_SKILL_FAILED: 'bestiary/GET_SKILL_FAILED',
  RECEIVE_BESTIARY_DATA: 'bestiary/RECEIVE_BESTIARY_DATA',
  SET_BESTIARY_PAGE: 'bestiary/SET_BESTIARY_PAGE'
};
